# Introduction to Python Matrices and NumPy #

Welcome to your first notebook of this specialization! In this notebook, you will use NumPy to create 2-D arrays and easily compute mathematical operations. NumPy (Numerical Python) is an open-source package that is widely used in science and engineering. Feel free to skip this notebook if you are already fluent with NumPy.

**After this assignment you will be able to:**
- Use Jupyter Notebook and its features. 
- Use NumPy functions to create arrays and NumPy array operations. 
- Use indexing and slicing for 2-D arrays.
- Find the shape of an array, reshape it and stack it horizontally and vertically.

**Instructions**
- You will be using Python 3.
- Follow along the cells using `Shift`+`Enter`. Alternatively, you can press `Run` in the menu. 

## Table of Contents ##
[About Jupyter Notebooks](#0)
- [1 - Basics of NumPy](#1)
    - [1.1 - Packages](#1-1)
    - [1.2 - Advantages of using NumPy arrays](#1-2)
    - [1.3 - How to create NumPy arrays](#1-3)
    - [1.4 - More on NumPy arrays](#1-4)
- [2 - Multidimensional arrays](#2)
    - [2.1 - Finding size, shape and dimension](#2-1)
- [3 - Array math operations](#3)
    - [3.1 - Multiplying vector with a scalar (broadcasting)](#3-1)
- [4 - Indexing and slicing](#4)
    - [4.1 - Indexing](#4-1)
    - [4.2 - Slicing](#4-2)
- [5 - Stacking](#5)
- [6 - Exercises](#6)

<a name='0'></a>
## About Jupyter Notebooks ##


Jupyter Notebooks are interactive coding journals（journals /ˈdʒɜː.nəlz/ 日志/日记 Coding journals 将代码、说明文字、图表整合在一起的可执行文档，像写日记一样记录数据科学探索过程。） that integrate live code, explanatory text, equations, visualizations and other multimedia resources, all in a single document. As a first exercise, run the test snippet below and the print statement cell for "Hello World".

In [2]:
msg = "Hello World,Today is sunnay in the ShenZhen"
print(f'{msg}')

Hello World,Today is sunnay in the ShenZhen


<a name='1'></a>
# 1 - Basics of NumPy #

NumPy is the main package for scientific computing in Python. It performs a wide variety of advanced mathematical operations with high efficiency. In this practice lab you will learn several key NumPy functions that will help you in future assignments, such as creating arrays, slicing, indexing, reshaping and stacking.

<a name='1-1'></a>
## 1.1 - Packages ##

Before you get started, you have to import NumPy to load its functions. As you may notice, even though there is no expected output, when you run this cell, the Jupyter Notebook imports the package (often referred to as the library) and its functions. Try it for yourself and run the following cell.

In [5]:
import numpy as np

<a name='1-2'></a>
## 1.2 - Advantages of using NumPy arrays ##

Arrays are one of the core data structures of the NumPy library, essential for organizing your data. You can think of them as a grid of values, all of the same type. If you have used Python lists before, you may remember that they are convenient`(convenient /kənˈviː.ni.ənt/ 方便的，便利的 Python lists are convenient 指的是 Python 列表使用起来很方便，因为可以存储不同类型的数据，且语法直观。)`, as you can store different data types. However, Python lists are limited in functions and take up more space and time to process than NumPy arrays.

NumPy provides an array object that is much faster and more compact than Python lists. Through its extensive API integration, the library offers many built-in functions that make computing much easier with only a few lines of code. This can be a huge advantage when performing math operations on large datasets. 

The array object in NumPy is called `ndarray` meaning 'n-dimensional array'. To begin with, you will use one of the most common array types: the one-dimensional array ('1-D'). A 1-D array represents a standard list of values entirely in one dimension. Remember that in NumPy, **all of the elements within the array are of the same type**.

In [9]:
one_dimensional_arr = np.array([10, 12])

In [10]:
print(one_dimensional_arr)

[10 12]


<a name='1-3'></a>
## 1.3 - How to create NumPy arrays ##

There are several ways to create an array in NumPy. You can create a 1-D array by simply using the function `array()` which takes in a list of values as an argument and returns a 1-D array.

In [11]:
# Create and print a NumPy array 'a' containing the elements 1, 2, 3.
a = np.array([1, 2, 3])
print(a)

[1 2 3]


Another way to implement an array is using `np.arange()`. This function will return an array of evenly spaced values within a given interval（这个函数将返回一个在给定区间内等间距取值的数组。）. To learn more about the arguments that this function takes, there is a powerful feature in Jupyter Notebook that allows you to access the documentation of any function by simply pressing `shift+tab` on your keyboard when clicking on the function. Give it a try for the built-in documentation of `np.arange()`. 

In [13]:
# Create an array with 3 integers, starting from the default integer 0.
b = np.arange(3)
print(b)

[0 1 2]


In [16]:
# Create an array that starts from the integer 1, ends at 20, incremented by 3.
# arange 包含起始值，不包含结束值（end-exclusive）
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


What if you wanted to create an array with five evenly spaced values in the interval from 0 to 100? As you may notice, you have 3 parameters that a function must take. One paremeter is the starting number, in  this case 0, the final number 100 and the number of elements in the array, in this case, 5. NumPy has a function that allows you to do specifically this by using `np.linspace()`.

In [17]:
lin_spaced_arr = np.linspace(0, 100, 5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


1. arange = "arrange"（排列），像 range() 一样，包头不包尾。
2. linspace = "linear space"（线性空间），头尾都包，中间等分。

 `arange` 的输出是整数，而 `linspace` 输出是浮点数,这是它们另一个重要区别

Did you notice that the output of the function is presented in the float value form (e.g. "... 25. 50. ...")? The reason is that the default type for values in the NumPy function `np.linspace` is a floating point (`np.float64`). You can easily specify your data type using `dtype`. If you access the built-in documentation for the functions, you will notice that most numpy functions take an optional parameter `dtype`. In addition to float, NumPy has several other data types such as `int`, and `char`. 

To change the type to integers, you need to set the dtype to `int`. You can do so, even in the previous functions. Feel free to try it out and modify the cells to output your desired data type. 

In [21]:
lin_spaced_arr_int = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr_int)

[  0  25  50  75 100]


In [22]:
c_int = np.arange(1, 20, 3, dtype=int)
print(c_int)

[ 1  4  7 10 13 16 19]


In [25]:
b_float = np.arange(10,dtype=float)
print(b_float)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [26]:
char_arr = np.array(["Welcome to Math for ML!"])
print(char_arr)
# Prints the data type of the array
print(char_arr.dtype) 

['Welcome to Math for ML!']
<U23


**`<U23` 是它的真实数据类型。这个数组用来存储一个最长为23个字符的Unicode字符串。**

In [27]:
type(char_arr[0])

numpy.str_

**`char_arr[0]` 的类型是 `numpy.str_`，它是 NumPy 对 Python 原生 `str` 的封装，用于在数组中高效存储 Unicode 字符串。**

In [28]:
print(isinstance(np.str_,str))

False
